export const TICKET_TYPE = {
    SWO: 'SWO_TASK',
    PM: 'PM_TASK',
    PMA: 'PRA'
}

export const TiCKET_STATE = {
    OPEN: 'OPEN',
    ASSIGNED: 'ASSIGNED',
    WORKINPROGRESS: 'WORK_IN_PROGRESS',
    WAITFORCLOSURE: 'AWAITING_CLOSURE',
    CLOSED: 'CLOSED',
    CANCEL: 'CANCEL',
    INPROGRESS: 'IN_PROGRESS'
}

export const ALARM_STATE = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  CANCEL: 'CANCEL',
  INPROGRESS: 'IN_PROGRESS'
}

export const ROLE = {
  NOC: 'NOC',
  FE: 'FE',
  FS: 'FS',
  ADMIN: 'ADMIN'
}

export const PRIORITIES = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MODERATE: 'MODERATE',
  LOW: 'LOW'
}

