import { Component } from '@angular/core';

@Component({
  selector: 'app-service-list',
  templateUrl: './service-list.component.html',
  styleUrl: './service-list.component.scss'
})
export class ServiceListComponent {
  services = [
    {
      id: '1',
      image: 'https://picsum.photos/400/300?random=1',
      title: 'Irrigation',
      available: true,
      address: 'Ferme de Ndiagne, Louga, Sénégal',
      lat: 15.6107,
      lng: -16.2414,
      description: 'Système d’irrigation moderne pour une gestion optimale de l’eau dans vos cultures.',
    },
    {
      id: '2',
      image: 'https://picsum.photos/400/300?random=2',
      title: 'Matériel Agricole',
      available: true,
      address: 'Zone Industrielle, Dakar, Sénégal',
      lat: 14.7167,
      lng: -17.4677,
      description: 'Matériel agricole de haute qualité pour faciliter vos travaux sur le terrain.',
    },
    {
      id: '3',
      image: 'https://picsum.photos/400/300?random=3',
      title: 'Semences Certifiées',
      available: true,
      address: 'Marché Central, Kaolack, Sénégal',
      lat: 14.1837,
      lng: -16.2539,
      description: 'Semences certifiées pour des rendements agricoles optimaux.',
    },
    {
      id: '4',
      image: 'https://picsum.photos/400/300?random=4',
      title: 'Formation en Techniques Agricoles',
      available: false,
      address: 'Centre de Formation, Thiès, Sénégal',
      lat: 14.7900,
      lng: -16.9261,
      description: 'Sessions de formation pour améliorer vos compétences agricoles.',
    },
    {
      id: '5',
      image: 'https://picsum.photos/400/300?random=5',
      title: 'Engrais Naturels',
      available: true,
      address: 'Ferme de Fatick, Fatick, Sénégal',
      lat: 14.3829,
      lng: -17.0317,
      description: 'Engrais naturels pour une agriculture respectueuse de l’environnement.',
    },
    {
      id: '6',
      image: 'https://picsum.photos/400/300?random=6',
      title: 'Installation de Serres',
      available: true,
      address: 'Quartier Agricole, Saint-Louis, Sénégal',
      lat: 16.0179,
      lng: -16.4896,
      description: 'Conception et installation de serres pour des cultures sous abri.',
    },
    {
      id: '7',
      image: 'https://picsum.photos/400/300?random=7',
      title: 'Analyse de Sol',
      available: true,
      address: 'Laboratoire Agricole, Ziguinchor, Sénégal',
      lat: 12.5833,
      lng: -16.2719,
      description: 'Analyse complète des sols pour déterminer les besoins spécifiques de vos cultures.',
    },
    {
      id: '8',
      image: 'https://picsum.photos/400/300?random=8',
      title: 'Assistance Technique',
      available: true,
      address: 'Bureau Agricole, Tambacounda, Sénégal',
      lat: 13.7670,
      lng: -13.6673,
      description: 'Support technique personnalisé pour améliorer vos pratiques agricoles.',
    },
    {
      id: '9',
      image: 'https://picsum.photos/400/300?random=9',
      title: 'Élevage Bovin',
      available: true,
      address: 'Ranch de Kolda, Kolda, Sénégal',
      lat: 12.8922,
      lng: -14.9408,
      description: 'Support pour l’élevage bovin : alimentation, santé et reproduction.',
    },
    {
      id: '10',
      image: 'https://picsum.photos/400/300?random=10',
      title: 'Pépinières',
      available: true,
      address: 'Pépinière de Rufisque, Rufisque, Sénégal',
      lat: 14.7128,
      lng: -17.2675,
      description: 'Plantes et jeunes arbres adaptés à différentes conditions climatiques.',
    },
    {
      id: '11',
      image: 'https://picsum.photos/400/300?random=11',
      title: 'Récolte Mécanisée',
      available: true,
      address: 'Ferme de Saint-Louis, Saint-Louis, Sénégal',
      lat: 16.0500,
      lng: -16.5000,
      description: 'Service de récolte mécanisée pour augmenter l’efficacité de vos exploitations.',
    },
    {
      id: '12',
      image: 'https://picsum.photos/400/300?random=12',
      title: 'Transformation des Produits',
      available: true,
      address: 'Usine Agroalimentaire, Kaolack, Sénégal',
      lat: 14.1827,
      lng: -16.2539,
      description: 'Transformation des produits agricoles pour une valeur ajoutée accrue.',
    },
    {
      id: '13',
      image: 'https://picsum.photos/400/300?random=13',
      title: 'Protection des Cultures',
      available: true,
      address: 'Agence Agricole, Mbour, Sénégal',
      lat: 14.4192,
      lng: -16.9664,
      description: 'Solutions pour protéger vos cultures contre les parasites et maladies.',
    },
    {
      id: '14',
      image: 'https://picsum.photos/400/300?random=14',
      title: 'Fumigation',
      available: true,
      address: 'Entrepôt Agricole, Fatick, Sénégal',
      lat: 14.3833,
      lng: -17.0333,
      description: 'Services de fumigation pour entrepôts et cultures en stockage.',
    },
    {
      id: '15',
      image: 'https://picsum.photos/400/300?random=15',
      title: 'Construction de Bassins',
      available: true,
      address: 'Ferme Aquatique, Louga, Sénégal',
      lat: 15.6097,
      lng: -16.2415,
      description: 'Construction de bassins pour pisciculture ou irrigation.',
    },
];

  
}
